Repository MarZazSoft/SuperTool, pull requests merged in 2025-04, with the labels that each got.

#25 TEST-Update-manual-trigger-release-add-sign-process
  .github/workflows/DeployTest.yml
Labels: chore

#26 TEST-Update-manual-trigger-release-add-install-android-sdk
  .github/workflows/DeployTest.yml
Labels: bug

#27 TEST-Update-manual-trigger-release-remove-steps-for-install-android-sdk
  .github/workflows/DeployTest.yml
Labels: bug

#28 TEST-Update-manual-trigger-release-remove-and-add-some-steps
  .github/workflows/DeployTest.yml
Labels: bug

#29 TEST-Update-manual-trigger-release-use-wzieba-action
  .github/workflows/DeployTest.yml
Labels: bug

#30 TEST-Update-manual-trigger-release-update-wzieba-action-version
  .github/workflows/DeployTest.yml
Labels: bug

#31 DEV-Update-branch-with-test-04-04-25
  .github/workflows/DeployTest.yml
  SuperTool/app/src/main/res/drawable/ic_launcher_foreground.xml
Labels: Update Branch, chore

#32 DEV-Update-splash-scren-and-add-animation
  SuperTool/app/src/main/java/com/marzazsoft/supertool/MainActivity.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/AppNavigation.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/MainScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/SplashScreen.kt
  SuperTool/app/src/main/res/values-normal/dimens.xml
Labels: enhancement

#33 DEV-Add-constraint-compose-library-and-add-login-ui
  SuperTool/app/build.gradle.kts
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/AppNavigation.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/MainScreen.kt
  SuperTool/gradle/libs.versions.toml
Labels: enhancement

#34 DEV-Update-login-screen-and-init-main-screen
  .github/workflows/CodeQlCheck.yml
  .github/workflows/DeployTest.yml
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/AppNavigation.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/NavigationScreens.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/MainScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/SplashScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/theme/Color.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/theme/Theme.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Constants.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Dimens.kt
  SuperTool/app/src/main/res/drawable/ic_disabled_visible_24.xml
  SuperTool/app/src/main/res/drawable/ic_eye_24.xml
  SuperTool/app/src/main/res/values-es-rMX/strings.xml
  SuperTool/app/src/main/res/values-normal/dimens.xml
  SuperTool/app/src/main/res/values/colors.xml
  SuperTool/app/src/main/res/values/strings.xml
  SuperTool/app/src/main/res/values/themes.xml
Labels: enhancement, chore

#35 TEST-UPDATE-BRANCH-04-11-25
  .github/workflows/CodeQlCheck.yml
  .github/workflows/DeployTest.yml
  SuperTool/app/build.gradle.kts
  SuperTool/app/src/main/java/com/marzazsoft/supertool/MainActivity.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/AppNavigation.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/NavigationScreens.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/MainScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/SplashScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/theme/Color.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/theme/Theme.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Constants.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Dimens.kt
  SuperTool/app/src/main/res/drawable/ic_disabled_visible_24.xml
  SuperTool/app/src/main/res/drawable/ic_eye_24.xml
  SuperTool/app/src/main/res/values-es-rMX/strings.xml
  SuperTool/app/src/main/res/values-normal/dimens.xml
  SuperTool/app/src/main/res/values/colors.xml
  SuperTool/app/src/main/res/values/strings.xml
  SuperTool/app/src/main/res/values/themes.xml
  SuperTool/gradle/libs.versions.toml
Labels: Update Branch

#36 DEV-Update-libraries-and-add-dependencies-injection
  SuperTool/app/build.gradle.kts
  SuperTool/app/src/main/AndroidManifest.xml
  SuperTool/app/src/main/java/com/marzazsoft/supertool/MyApp.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/di/KoinModule.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/viewModels/LoginViewModel.kt
  SuperTool/build.gradle.kts
  SuperTool/gradle/libs.versions.toml
  SuperTool/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, chore

#37 DEV-Update-time-splash
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Constants.kt
Labels: chore

#38 DEV-Add-firebase-auth-libraries
  SuperTool/app/build.gradle.kts
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/viewModels/LoginViewModel.kt
  SuperTool/gradle/libs.versions.toml
Labels: enhancement

#39 DEV-Add-google-button
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/MainScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/theme/Color.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Dimens.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/viewModels/LoginViewModel.kt
  SuperTool/app/src/main/res/drawable/ic_google.xml
  SuperTool/app/src/main/res/values-es-rMX/strings.xml
  SuperTool/app/src/main/res/values/strings.xml
Labels: enhancement

#40 DEV-add-sign-in-with-google-account
  .github/workflows/CodeQlCheck.yml
  .github/workflows/DeployTest.yml
  SuperTool/app/build.gradle.kts
  SuperTool/app/proguard-rules.pro
  SuperTool/app/src/main/AndroidManifest.xml
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Constants.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/viewModels/LoginViewModel.kt
  SuperTool/gradle/libs.versions.toml
Labels: enhancement

#41 DEV-Add-common-loader-and-use-it-in-google-sign-in
  SuperTool/app/src/main/java/com/marzazsoft/supertool/di/KoinModule.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/AppNavigation.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/NavigationScreens.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/HomeScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/HomeScreenGuest.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/MainScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/SplashScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/share/SuperToolProgressIndicator.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/theme/Color.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/ApiStatus.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Dimens.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/viewModels/MainViewModel.kt
  SuperTool/app/src/main/res/drawable/ic_email.xml
  SuperTool/app/src/main/res/values-es-rMX/strings.xml
  SuperTool/app/src/main/res/values/strings.xml
Labels: enhancement

#42 DEV-Add-bottom-menu-and-his-navigation-to-home-screen
  SuperTool/app/src/main/java/com/marzazsoft/supertool/models/ItemNavigation.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/AppNavigation.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/HomeNavigation.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/NavigationScreens.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/HomeScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/MainScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/ProfileScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/SettingsScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/SplashScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/ToolsScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/share/BottomMenu.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/share/SuperToolProgressIndicator.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/CommonFunctions.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Constants.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Dimens.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/viewModels/MainViewModel.kt
  SuperTool/app/src/main/res/drawable/ic_guest.xml
  SuperTool/gradle/libs.versions.toml
Labels: enhancement

#43 DEV-Bugfix-in-home-screen-navigation
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/HomeScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/share/BottomMenu.kt
Labels: bug

#44 DEV-Add-simple-alert-dialog-and-readme
  README.md
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/AppNavigation.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/navigation/NavigationScreens.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/HomeScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/HomeScreenGuest.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/LoginScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/MainScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/ProfileScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/SettingsScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/SplashScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/ToolsScreen.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/share/BottomMenu.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/share/SimpleAlert.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/share/SuperToolProgressIndicator.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/CommonFunctions.kt
  SuperTool/app/src/main/java/com/marzazsoft/supertool/utils/Dimens.kt
  SuperTool/app/src/main/res/values-es-rMX/strings.xml
  SuperTool/app/src/main/res/values/strings.xml
  SuperTool_1.0.png
Labels: enhancement

#46 DEV-Fix-navegation-when-is-in-guest-mode
  .github/workflows/CodeQlCheck.yml
  .github/workflows/DeployTest.yml
  .gitignore
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/HomeScreen.kt
Labels: bug

#47 TEST-Update-branch-with-develop-04-30-2025
  .github/workflows/CodeQlCheck.yml
  .github/workflows/DeployTest.yml
  .gitignore
  SuperTool/app/src/main/java/com/marzazsoft/supertool/ui/screens/HomeScreen.kt
Labels: Update Branch

#48 TEST-Fix-deploy-github-action
  .github/workflows/DeployTest.yml
Labels: bug
